adds Allen Cell Segmenter
chanzuckerberg/napari-plugin-alfa-cohort pull request #18
Opened 2021-01-22 00:58 UTC by neuromusic

How does this look, @jxchen01 & @benjijamorris?

If you can suggest language for the "Purpose" section, I'm happy to add it in.

2021-01-22 17:33 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +2. Select a workflow which is tuned for a particular cell structure
Check the workflow look-up tablle where each workflow is tuned for a particular structure. Pick the one showing the most similar morphology to user's data

2021-01-22 18:30 UTC, jxchen01 requested changes

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +7. Analyze the results to extract statistics of cell structures
item 7 is out of the scopt of the Alfa Cohort

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +3. [Ultra Stretch] Integrating with ML model. Curation of pass/fail (not painting). Use case: different areas of image may need different algorithm. Then a set of training data is ready for training.
I would suggest "Curation of pass/fail (not painting)" --> something like "Curation using the merging or sorting curator (see paper for details)"

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +I should be able to read this alone and communicate the value to someone else.
Making a large number of 3D intracelluar structure segmentation algorithms in Allen Cell and Structure Segmenter accesible and easy to tweak for users at any level.

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +title: Allen Cell Segmenter
we just updated our formal name as "Allen Cell and Structure Segmenter"

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +title: Allen Cell Segmenter
I would suggestion somthing similar to this: 

Allen Cell and Structure Segmenter (Segmenter)

Then, anything down below can directly use "Segmenter"

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +title: Allen Cell Segmenter
@Kimcmetzler can you comment on this?

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +
The large collection of fluorescently-labeled cell lines from the [Allen Cell Collection](https://www.allencell.org/cell-catalog.html) fosters the development of a large set of image processing workflows that serves as a good resource for biologists to use in many different applications.

2021-01-22 18:30 UTC, jxchen01 commented on projects/allen-cell-segmenter.md
> +
The development of this plugin will enable a broader community of scientists to perform 3D segmentation on their images and aligns with the mission of the [Allen Institute for Cell Science](allencell.org) for open science.

2021-01-22 18:30 UTC, jxchen01 commented on projects/index.md
> +# [Allen Cell Segmenter](projects/allen-cell-segmenter)
`[Allen Cell and Structure Segmenter](projects/allen-cell-segmenter)`

2021-01-22 20:07 UTC, Kimcmetzler commented on projects/allen-cell-segmenter.md
> +title: Allen Cell Segmenter
Yes, please use the title, "Allen Cell and Structure Segmenter", and "Segmenter" as the abbreviated title in sections below .

2021-01-26 00:53 UTC, neuromusic commented on projects/allen-cell-segmenter.md
> +7. Analyze the results to extract statistics of cell structures
I assume that this is part of their broader workflow, but out of scope for integrating into napari during the Alfa Cohort?

2021-01-26 00:55 UTC, neuromusic commented on projects/allen-cell-segmenter.md
> +title: Allen Cell Segmenter
👍

2021-01-26 01:00 UTC, neuromusic commented on projects/allen-cell-segmenter.md
> +7. Analyze the results to extract statistics of cell structures
Added a note to clarify that this would need to happen outside of napari

2021-01-26 01:01 UTC, neuromusic commented
OK, made the requested changes. LMK how it looks @jxchen01!

2021-01-27 17:26 UTC, jxchen01 approved these changes
thanks!

2021-01-27 17:27 UTC, jxchen01 approved these changes

2021-01-27 17:27 UTC, jxchen01 approved these changes

2021-01-28 04:34 UTC, merged